steps:

# build the container
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag=gcr.io/$PROJECT_ID/${_PROJECT_NAME}:${_BRANCH}'
  - '.'

# tag the container
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'tag'
  - 'gcr.io/$PROJECT_ID/${_PROJECT_NAME}:${_BRANCH}'
  - 'gcr.io/$PROJECT_ID/${_PROJECT_NAME}:${_BUILD_SHA}'

# images
images:
- 'gcr.io/$PROJECT_ID/${_PROJECT_NAME}:${_BRANCH}'
- 'gcr.io/$PROJECT_ID/${_PROJECT_NAME}:${_BUILD_SHA}'
